### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by IRMobydick** [clickyab/android-sample#28]
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:309)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
    Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
       at org.json.JSONTokener.nextValue(JSONTokener.java:94)
       at org.json.JSONObject.<init>(JSONObject.java:156)
       at org.json.JSONObject.<init>(JSONObject.java:173)
       at com.clickyab.c.b$b.a(Unknown Source)
       at com.clickyab.c.b$b.doInBackground(Unknown Source)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by IRMobydick** [comment]
@fzerorubigd @psamim 
What the hell is going on there?
I've open this damn issue 5 days ago! How much progress you have made so far!
nothing! just 3 days ago @fzerorubigd assign this damn issue to @psamim !!!!

Our users experience annoying behavior from your SDK!!!
- Crash on android 6.0.1!
- Crash on internet connection lost
- Crash on Memory Leak

Just to feel better our unfavorable situation, look at this:

![crash](https://cloud.githubusercontent.com/assets/4468890/22439793/418df50c-e746-11e6-8364-2ab0e1045ca9.jpg)

Who will be responsible to our user loss?

**Comment by psamim** [comment]
@IRMobydick Null pointer exception is fixed and some preventive actions on possible leaks are added in version 1.2.9.

**Comment by psamim** [comment]
@IRMobydick Please keep us updated on if it has solved the issue.

**Comment by IRMobydick** [comment]
@psamim Thanks Bro! We're going to implement it, I'll keep you up 👍
